#!/bin/bash
# Create an "AI Switchboard.app" bundle on the user's Desktop.
# macOS / Linux equivalent of tools/install-desktop-shortcut.ps1.
#
# Usage (run once from anywhere; usually from the repo root):
#   bash tools/install-desktop-app.sh
#
# To install somewhere other than the Desktop:
#   INSTALL_DIR="$HOME/Applications" bash tools/install-desktop-app.sh
#
# Re-running overwrites the existing bundle — idempotent.
#
# What this produces:
#   <INSTALL_DIR>/AI Switchboard.app/
#     Contents/
#       Info.plist                    (CFBundleIconFile=icon, NSHighResolutionCapable)
#       MacOS/launcher                (bash; cd <repo>; exec python3 launch.pyw)
#       Resources/icon.icns           (copied from <repo>/ai-switchboard.icns)
#
# First-time Gatekeeper prompt: macOS will warn "Apple cannot check this app
# for malicious software" the first time. Right-click the .app -> Open -> Open
# dismisses that permanently for your user. (Code-signing is a packaging
# concern for distribution to strangers, not for personal install.)
#
# The repo path is baked into the launcher at install time. If you move the
# repo, re-run this script.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

LAUNCH_PYW="$REPO_DIR/launch.pyw"
ICON_ICNS="$REPO_DIR/ai-switchboard.icns"
[ -f "$LAUNCH_PYW" ] || { echo "ERROR: launch.pyw not found at $LAUNCH_PYW" >&2; exit 1; }
[ -f "$ICON_ICNS"  ] || { echo "ERROR: ai-switchboard.icns not found at $ICON_ICNS" >&2; exit 1; }

PYTHON3="$(command -v python3 || true)"
if [ -z "$PYTHON3" ]; then
    echo "ERROR: python3 not on PATH. Install Python 3.13+ and re-run." >&2
    exit 1
fi

DEST="${INSTALL_DIR:-$HOME/Desktop}"
APP_PATH="$DEST/AI Switchboard.app"

echo "Installing to: $APP_PATH"

# Wipe any prior install and rebuild.
rm -rf "$APP_PATH"
mkdir -p "$APP_PATH/Contents/MacOS"
mkdir -p "$APP_PATH/Contents/Resources"

cp "$ICON_ICNS" "$APP_PATH/Contents/Resources/icon.icns"

# Info.plist. Standard bundle metadata + NSHighResolutionCapable for sharp
# rendering on Retina displays. No LSUIElement — we want a Dock icon.
cat > "$APP_PATH/Contents/Info.plist" <<INFO_PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>AI Switchboard</string>
    <key>CFBundleDisplayName</key>
    <string>AI Switchboard</string>
    <key>CFBundleIdentifier</key>
    <string>com.aiswitchboard.launcher</string>
    <key>CFBundleVersion</key>
    <string>0.1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
    <key>CFBundleExecutable</key>
    <string>launcher</string>
    <key>CFBundleIconFile</key>
    <string>icon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
INFO_PLIST

# The launcher itself. The .app's main executable. Hardcodes the repo path
# and python3 path baked at install time. The actual work (uvicorn spawn,
# /api/health poll, browser open) lives in launch.pyw which is identical
# across platforms.
#
# Unquoted heredoc so $REPO_DIR and $PYTHON3 get expanded NOW (bake in the
# install-time values). \$REPO_DIR / \$PYTHON3 references inside the body
# are preserved literally for the launcher to expand at runtime.
cat > "$APP_PATH/Contents/MacOS/launcher" <<LAUNCHER_BODY
#!/bin/bash
# AI Switchboard .app launcher. Generated by tools/install-desktop-app.sh.
# Repo path baked in at install time; re-run the installer if the repo moves.
REPO_DIR="$REPO_DIR"
PYTHON3="$PYTHON3"
if [ ! -d "\$REPO_DIR" ]; then
    osascript -e 'display dialog "AI Switchboard repo no longer at the path baked into this .app bundle.\nRe-run tools/install-desktop-app.sh from the repo." buttons {"OK"} default button "OK" with icon stop' >/dev/null 2>&1
    exit 1
fi
if [ ! -x "\$PYTHON3" ]; then
    osascript -e 'display dialog "python3 not found at the path baked into this .app bundle.\nInstall Python 3.13+ and re-run tools/install-desktop-app.sh." buttons {"OK"} default button "OK" with icon stop' >/dev/null 2>&1
    exit 1
fi
cd "\$REPO_DIR" || exit 1
exec "\$PYTHON3" launch.pyw
LAUNCHER_BODY

chmod +x "$APP_PATH/Contents/MacOS/launcher"

# Clear macOS quarantine attribute if present — otherwise Gatekeeper's
# warning is harsher than it needs to be for a locally-built bundle.
# Failure is non-fatal (xattr may not be available, or no attr is set).
xattr -dr com.apple.quarantine "$APP_PATH" 2>/dev/null || true

echo ""
echo "Created AI Switchboard.app at: $APP_PATH"
echo ""
echo "  python3:      $PYTHON3"
echo "  repo:         $REPO_DIR"
echo "  icon:         $APP_PATH/Contents/Resources/icon.icns"
echo "  executable:   $APP_PATH/Contents/MacOS/launcher"
echo ""
echo "Double-click the .app icon to launch. To pin it to the Dock, drag"
echo "the .app onto the Dock once it's open."
echo ""
echo "First-time Gatekeeper warning: if macOS says \"Apple cannot check this"
echo "app for malicious software\", right-click the .app -> Open -> Open."
echo "Dismisses the warning permanently for your user account."
